# makefile for Asembli4

cc =gcc
CFLAGS =-g -ansi -Wall -pedantic
CFLAGS2 =-c -ansi -Wall -pedantic
LDFLAGS =-o


FILE = remove.o
HEDER =







remove: $(FILE) $(HEDER)
	$(cc) $(CFLAGS) $< $(LDFLAGS) $@


%.o: %.c
	$(cc) $(CFLAGS2) $< $(LDFLAGS) $@ 








